<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Combos</name>
   <tag></tag>
   <elementGuidId>9b036f92-e8e7-4901-ae43-f17935ff97bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.category-item > button[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36caec3f-4f26-479b-9636-bad43befd8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57e9798e-98ca-4467-bfb4-0a5b6383ab09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>category-item-button</value>
      <webElementGuid>19b3193e-b548-47f8-b408-7fed498c35fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Combos</value>
      <webElementGuid>1184253a-12bc-443d-8919-8c6b53bc68ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categories-container&quot;)/section[@class=&quot;container-fluid&quot;]/div[@class=&quot;row page-flex-top&quot;]/div[@class=&quot;col-lg-8 col-md-8 col-sm-8 col-xs-12 categories-menu-container&quot;]/div[@class=&quot;menu-grid&quot;]/div[@class=&quot;row menu-grid-flex&quot;]/div[@class=&quot;category-item&quot;]/button[1]</value>
      <webElementGuid>904d903e-bc6c-4152-b16e-e1a2cab7bc8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>865939ce-b4bc-47a1-9127-038c1df4cf9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='categories-container']/section/div/div/div[2]/div/div/button</value>
      <webElementGuid>e955f0a3-4fe2-4268-8f14-ac8de1a705ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunch/Dinner'])[1]/following::button[1]</value>
      <webElementGuid>af34b4cf-b4ba-4459-873a-cffe56315033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stay hungry, my friends.'])[1]/following::button[1]</value>
      <webElementGuid>1d9d431f-dae3-426a-80a6-ac4bb38e8c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hamburgers'])[1]/preceding::button[1]</value>
      <webElementGuid>3060ed26-f30f-4e29-947c-ccb5e8342e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/button</value>
      <webElementGuid>9b583847-3af1-4093-aee9-01e052e4804d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Combos' or . = 'Combos')]</value>
      <webElementGuid>88273f43-2965-4630-820c-d811eb09c4a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
