<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Company</name>
   <tag></tag>
   <elementGuidId>7eda90a0-eb09-4449-876c-6547a38ff490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='block-wendys-main-main-menu']/ul/li[3]/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>470504e4-a18a-4e03-a6b8-51bdd094aa94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/who-we-are</value>
      <webElementGuid>7289fcda-edeb-4bbe-a1d5-628fc11d78a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>ed8eb5ef-8f64-4f89-b715-e126d45dc245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/21</value>
      <webElementGuid>365515b1-70e1-40fb-9d97-521a374bc137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>bb950ff7-ec39-464a-9f2d-37f34189f945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-wendys-main-main-menu&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item&quot;]/span[@class=&quot;mobile&quot;]/a[1]</value>
      <webElementGuid>32837314-c164-422e-af64-3b5eb0a2d776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='block-wendys-main-main-menu']/ul/li[3]/span[2]/a</value>
      <webElementGuid>f26d018a-98d6-45c8-8a6b-d096f12d15b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Company')]</value>
      <webElementGuid>2ab97d13-d311-4498-83ac-53f59ec54d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who We Are'])[1]/following::a[1]</value>
      <webElementGuid>5adc78dd-9c03-49ae-946d-c30e894386c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Values'])[1]/following::a[2]</value>
      <webElementGuid>75fcf698-9295-4a63-a5ad-e9620584049d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Jobs'])[1]/preceding::a[1]</value>
      <webElementGuid>9f18b319-7dd1-4439-8697-a54ef8e81b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs'])[1]/preceding::a[2]</value>
      <webElementGuid>1f6003e3-d261-43e1-b4b1-90aac151acdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company']/parent::*</value>
      <webElementGuid>d8e22cad-170c-4a96-8a5c-50f3903973d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/who-we-are')])[2]</value>
      <webElementGuid>2999c919-255d-4e94-837e-5a3ec2fde747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/ul/li[3]/span[2]/a</value>
      <webElementGuid>ee6cafe5-fcc6-4c97-b351-0e366e40bfac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/who-we-are' and (text() = 'Company' or . = 'Company')]</value>
      <webElementGuid>34c15f8c-47df-4e35-a3fe-f07653f0c1f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
