<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jobs</name>
   <tag></tag>
   <elementGuidId>6bbf43da-c083-48b2-82db-fae097e001c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='block-wendys-main-main-menu']/ul/li[4]/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a1b0c04-4c36-4718-b6f9-35495ff883c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://wendys-careers.com/</value>
      <webElementGuid>3afa36d2-a7db-4273-a267-6c4514b48227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jobs</value>
      <webElementGuid>b96192d7-f4a8-4336-9b7a-81781b3cabcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-wendys-main-main-menu&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item&quot;]/span[@class=&quot;mobile&quot;]/a[1]</value>
      <webElementGuid>a8a78156-3341-4d40-aa23-1f4fed6169df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='block-wendys-main-main-menu']/ul/li[4]/span[2]/a</value>
      <webElementGuid>1f777b5f-e0e3-4285-a4e5-ff9fe7d2436a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Jobs')])[2]</value>
      <webElementGuid>a5cee623-61f6-46c9-bb00-095035a31d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Jobs'])[1]/following::a[1]</value>
      <webElementGuid>554f8f46-30a7-4c5c-a456-47ad660518b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::a[2]</value>
      <webElementGuid>63ff3c5a-5640-46b4-8756-13656900f114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utility 2'])[1]/preceding::a[1]</value>
      <webElementGuid>7b5ea696-eff5-4d74-81e4-40c993aae19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Our Menu'])[1]/preceding::a[1]</value>
      <webElementGuid>f328c0e3-46ff-4b1f-9b29-d872f771f8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jobs']/parent::*</value>
      <webElementGuid>b4306fc0-d280-4fe7-877e-2312414e9d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://wendys-careers.com/')])[2]</value>
      <webElementGuid>94a76c20-4efb-42a3-8174-f87a11420fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/ul/li[4]/span[2]/a</value>
      <webElementGuid>95d128d1-e004-470d-89ac-fdaab94ac0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://wendys-careers.com/' and (text() = 'Jobs' or . = 'Jobs')]</value>
      <webElementGuid>4057bab5-5aa1-4092-906c-fc58d6c38f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
