<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Menu</name>
   <tag></tag>
   <elementGuidId>f2e5d154-7b14-4a58-9e4c-98fb2a63d669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mobile > a[title=&quot;Our menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;block-wendys-main-main-menu&quot;]/ul/li[1]/span[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b2cd400-b70c-482e-a021-1269ebf973f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://order.wendys.com/categories?site=menu&amp;lang=en_US</value>
      <webElementGuid>ac0a5f25-0739-4959-a542-75d0de04c4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>f8b543c9-0b1a-4bd8-8067-51de19d34697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking</name>
      <type>Main</type>
      <value>{&quot;event&quot;:&quot;eventClick&quot;,&quot;eventCategory&quot;:&quot;View our menu category&quot;,&quot;eventAction&quot;:&quot;View our menu action&quot;,&quot;eventLabel&quot;:&quot;View our menu label&quot;}</value>
      <webElementGuid>6fdafb1f-7f5f-4386-9c8c-c2c46e1662c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Our menu</value>
      <webElementGuid>df3b9de8-b4bb-4151-8a6a-1e5732a07280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>7f3bb393-ee52-4fdd-9bfb-9e2c98e15892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-wendys-main-main-menu&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item&quot;]/span[@class=&quot;mobile&quot;]/a[1]</value>
      <webElementGuid>957251fb-68a8-4e3c-8e41-c3f58292291d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='block-wendys-main-main-menu']/ul/li/span[2]/a</value>
      <webElementGuid>464da6ac-abdb-4ffa-9ac9-c186f13d9b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Menu')])[2]</value>
      <webElementGuid>9a79f0bb-0773-4727-bc74-32dae05c17fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View our Menu'])[1]/following::a[1]</value>
      <webElementGuid>0acd84a6-54c9-4dd6-a926-8ce7786ba35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main navigation'])[1]/following::a[2]</value>
      <webElementGuid>8386327c-26e6-4451-a991-1d9b1d3ddb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What We Value'])[1]/preceding::a[1]</value>
      <webElementGuid>8d371b58-f6f9-4b2c-a0be-2c90a2d8b4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Values'])[1]/preceding::a[2]</value>
      <webElementGuid>0d1dc08d-37f1-4c1a-a552-35b914ee25ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>9aad4e6f-a745-4aa3-b874-5f26f00d21d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://order.wendys.com/categories?site=menu&amp;lang=en_US')])[2]</value>
      <webElementGuid>6db4a2af-08f4-4c66-8c65-9ba851fa449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/ul/li/span[2]/a</value>
      <webElementGuid>bb5bf825-d345-4ac0-b35f-7b4f7ca4e362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://order.wendys.com/categories?site=menu&amp;lang=en_US' and @title = 'Our menu' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>a8be2854-0c3b-4d6b-b815-03a3f237d170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
