<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Interstellar</name>
   <tag></tag>
   <elementGuidId>3ad112e7-cc06-4347-84dd-71ad6fb203ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.js-movie-detail-title.movie-detail__title.dark__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mop-info-wrap']/section/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>75f28446-43f6-42fb-b495-acabdd7c6e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-movie-detail-title movie-detail__title dark__text</value>
      <webElementGuid>e12f2b69-b58f-45d7-b3b9-df7f4974368f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interstellar</value>
      <webElementGuid>c31f15d3-781e-4449-9a07-3ea9a73dd525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mop-info-wrap&quot;)/section[@class=&quot;movie-detail__info-bloc&quot;]/div[@class=&quot;movie-detail__movie-info&quot;]/h1[@class=&quot;js-movie-detail-title movie-detail__title dark__text&quot;]</value>
      <webElementGuid>8d229ba2-928a-4988-bb87-44c185362bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mop-info-wrap']/section/div[2]/h1</value>
      <webElementGuid>39568be0-d6a3-4b3b-8d05-dbdf4ff130a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to favorite movies'])[1]/following::h1[1]</value>
      <webElementGuid>547bd51b-7ba0-449e-b62a-858d2e71c775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Tickets'])[1]/following::h1[1]</value>
      <webElementGuid>45ccdd32-9abc-4aee-b8d6-acd78bcfb713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movie Rating'])[1]/preceding::h1[1]</value>
      <webElementGuid>e24161c8-1d91-4250-b53f-a41ce1249f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Interstellar']/parent::*</value>
      <webElementGuid>5044c6e0-0b00-484f-b061-6699ec3dc85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>25220f94-1a47-4bfc-b10c-6c3357e9c38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Interstellar' or . = 'Interstellar')]</value>
      <webElementGuid>ea1394d3-43f5-415d-9c29-02263cff948a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
