<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_OFFERS</name>
   <tag></tag>
   <elementGuidId>d76784d4-2312-4f0b-baa1-632a692439ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.offers__heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='page']/main/div/section/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>68b33c69-51b5-4cbf-bcff-cd7a7904b2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>offers__heading</value>
      <webElementGuid>33509ee2-43e8-4dd1-8b9a-63daccd9e6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OFFERS</value>
      <webElementGuid>998103ef-054d-491c-ae2e-abbf1ba05f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/main[@class=&quot;emu__content offers dark__section&quot;]/div[@class=&quot;row&quot;]/section[@class=&quot;tablet-width-100 width-75&quot;]/h1[@class=&quot;offers__heading&quot;]</value>
      <webElementGuid>1e915442-4855-43c6-b361-8f77e3105150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='page']/main/div/section/h1</value>
      <webElementGuid>74db60c1-d1c6-4950-8187-c5733942d1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to next offer'])[1]/following::h1[1]</value>
      <webElementGuid>31fc2105-13c3-462f-b127-18176e27a933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Be the First to Watch! Film Revealed @ Showtime'])[2]/following::h1[1]</value>
      <webElementGuid>bf414528-b032-4af4-bd0f-568fb4c2e535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Offers'])[1]/preceding::h1[1]</value>
      <webElementGuid>65da804d-97fc-4093-a378-7ada01e3eb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple Pay Wednesday image link'])[1]/preceding::h1[1]</value>
      <webElementGuid>6de6a032-4fbc-49e3-b939-2adcda286c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OFFERS']/parent::*</value>
      <webElementGuid>b691777f-3e10-4552-82eb-3891fec47824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f6258049-e088-427e-b225-a6bf2ec47fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'OFFERS' or . = 'OFFERS')]</value>
      <webElementGuid>19bcc462-0a8f-45f6-819a-070f48453c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
