<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>6b4c1307-2823-4d7f-b216-f8a38054fa70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#find-search-input-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='find-search-input-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Press enter to search&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>219bc0df-009d-4205-9a64-b08225dd9a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>find-search-input-submit</value>
      <webElementGuid>71e049b8-7efe-421e-ac61-b9e96711895b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e21351b4-0d78-45d1-9366-adf8b74b367e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9d87f195-33a7-41c8-8f18-48a178b7fd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Press enter to search</value>
      <webElementGuid>7213d204-e686-460a-b4c4-43508b1e453b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>74e97a3f-49b1-418d-b268-e3f22fa938ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;find-search-input-submit&quot;)</value>
      <webElementGuid>45860601-e1a6-4717-8767-ecaa8d1c010e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='find-search-input-submit']</value>
      <webElementGuid>218ba1bd-409d-4d35-9ebb-4201f89b4580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div/button</value>
      <webElementGuid>def3566f-2b96-4ca7-a88c-d7990fca249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILTER LOCATIONS'])[1]/preceding::button[1]</value>
      <webElementGuid>f795e4f2-f3e8-4669-b356-2b6f99d4e751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>40e22572-b7f2-48ad-b6c9-25ac61af0a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'find-search-input-submit' and @type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>caa15918-3095-4c4f-8b3a-1231c9158492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
