<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Order here</name>
   <tag></tag>
   <elementGuidId>5d90219d-3641-4758-9711-1d59b39b9ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#find-order-button-4823</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='find-order-button-4823']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#find-order-button-4823 >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e4bac16-98c0-4e1d-a493-d5aadedd8b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>find-order-button-4823</value>
      <webElementGuid>0051e064-beab-462d-8358-6a78cc50a666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>633acd5a-31cd-4a46-a7d9-ad2a446ea5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary order-button</value>
      <webElementGuid>26410ff5-f35a-43d6-acbf-cebbd58368f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order here</value>
      <webElementGuid>fd2838eb-dc18-4d7b-9b2c-3276f2820009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;common-header&quot;]/div[@class=&quot;main-content-container margin-adjust-for-sub-header&quot;]/div[@class=&quot;order-location-container&quot;]/div[@class=&quot;container order-container-padding-left&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;search-container&quot;]/div[@class=&quot;map-container&quot;]/div[@class=&quot;result-map-container&quot;]/div[@class=&quot;col-xs-12 col-sm-4 no-padding&quot;]/div[@class=&quot;results-container&quot;]/div[@id=&quot;ada-result-4823&quot;]/div[@class=&quot;buttons&quot;]/div[1]/div[1]/button[@id=&quot;find-order-button-4823&quot;]</value>
      <webElementGuid>cc8180f7-e387-441c-ade7-76a403c31166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='find-order-button-4823']</value>
      <webElementGuid>aca9ef12-66eb-4c77-b2ff-4c8a2874714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ada-result-4823']/div[3]/div/div/button</value>
      <webElementGuid>0146b074-fba2-427f-b525-cc9f28269a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST. CLOUD - 390'])[1]/following::button[1]</value>
      <webElementGuid>09294276-cd5c-4b62-bdbb-1ce06fa1b7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Map'])[1]/following::button[1]</value>
      <webElementGuid>71be90d0-c02f-40ba-8136-56668d3c2d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order here'])[2]/preceding::button[1]</value>
      <webElementGuid>13d1aa0e-9086-4497-8051-e1816a1fca4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HWY 192 @ PARTIN SETTLEMENT'])[1]/preceding::button[2]</value>
      <webElementGuid>341a51c0-afd0-40a0-add9-d7a5da61e500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order here']/parent::*</value>
      <webElementGuid>f5145838-07a9-45d9-bd86-0b611698dc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>db93a431-dfe0-4e6c-9e3d-af562d51d46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'find-order-button-4823' and @type = 'button' and (text() = 'Order here' or . = 'Order here')]</value>
      <webElementGuid>4b01fd32-b577-4118-80de-bd642c636f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
