<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pick Up Your Order_find-search-input-text_1</name>
   <tag></tag>
   <elementGuidId>3628eb7e-f7fc-4cf0-b3b0-684e0b95d70d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#find-search-input-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='find-search-input-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter City, State, or Zipcode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e002c96-cc41-4a34-94d0-a7dd7b7db60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>find-search-input-text</value>
      <webElementGuid>364a1d60-658e-4584-87cd-248afa6fe450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>38777023-1cfc-4431-a8a7-8415bdee48d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-bar</value>
      <webElementGuid>0f6b3564-5a0c-47f1-a4e5-dbd6fc6b1527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter City, State, or Zipcode</value>
      <webElementGuid>bb070cf3-08b6-4424-9d8f-c7156161859f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter City and State or Zipcode to find a Wendy's location</value>
      <webElementGuid>0f1231d1-c10c-4c7c-ab88-0bf7f5938d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>7181201d-3211-4250-989a-b5999b599892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>50d44db1-14e0-49a3-ae7c-256f5266b5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;find-search-input-text&quot;)</value>
      <webElementGuid>6fd535dd-e380-4ab5-a50f-7b46b5c57d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='find-search-input-text']</value>
      <webElementGuid>25b8d038-c40b-4c38-af23-33fc9d438c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div/input</value>
      <webElementGuid>2e9661d9-c596-48eb-a382-36b5f012dc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>44e944cb-8c63-4822-9abb-0237be36536a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'find-search-input-text' and @type = 'search' and @placeholder = 'Enter City, State, or Zipcode' and @title = 'Search']</value>
      <webElementGuid>12dc88eb-dd17-4e3d-828d-786bf4f2ea34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
