<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find a Job</name>
   <tag></tag>
   <elementGuidId>ff7722b4-4f6d-4c75-8603-104f6bb3984f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.blue.wide</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='index']/section/article/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a68395d-becf-4142-b044-59a61a5953bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button blue wide</value>
      <webElementGuid>f5a44384-e451-4935-a111-e4c5a375274e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50d4e181-6493-4c9b-8de0-8ffb18dc9027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job-search</value>
      <webElementGuid>585c0677-f87a-4a25-ab09-f6f4e9a97a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find a Job</value>
      <webElementGuid>bb6456f6-9cb1-4711-bb45-9fcfd7480771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index&quot;)/section[@class=&quot;intro&quot;]/article[@class=&quot;content&quot;]/div[@class=&quot;copy&quot;]/div[@class=&quot;button-container aos-init aos-animate&quot;]/a[@class=&quot;button blue wide&quot;]</value>
      <webElementGuid>94a191a8-c37c-4fcd-a4d7-bc8d6eb2e6d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='index']/section/article/div[2]/div[2]/a</value>
      <webElementGuid>76c70ce8-38fd-425b-8ade-9e432ca727c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find a Job')]</value>
      <webElementGuid>18b504d3-fdab-4a3d-93c1-9b12c260e2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keep it real,'])[1]/following::a[1]</value>
      <webElementGuid>95c002ca-cbda-4b54-a11c-aac87a0796b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you wanna'])[1]/following::a[1]</value>
      <webElementGuid>25e6c074-e666-4145-8678-230deca2f28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page down to next section'])[1]/preceding::a[1]</value>
      <webElementGuid>f8331bee-33b3-4785-9c92-dcb53cd1e316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/preceding::a[2]</value>
      <webElementGuid>0a539346-b82a-4f22-a03c-233d69b3c4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find a Job']/parent::*</value>
      <webElementGuid>fe85a2cd-0b26-4ce3-aeb7-34a6146db851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/job-search')])[3]</value>
      <webElementGuid>0c18af1e-80a9-418b-987c-6574786445ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>74e01ef1-a99d-4403-97ae-153f7e43d6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job-search' and (text() = 'Find a Job' or . = 'Find a Job')]</value>
      <webElementGuid>372ddc1a-4988-4f52-a7d9-c03566a421cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
