<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wendys uses tracking technologies such _b047f5</name>
   <tag></tag>
   <elementGuidId>a0757401-cb6f-43b3-9e4e-7da8219bb8c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onetrust-policy-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onetrust-policy-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4586fa9-6f4e-4624-aa3d-5d0b90645669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onetrust-policy-text</value>
      <webElementGuid>0caa48b6-7eee-4f9f-9b23-955ea6cbedc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wendy's uses tracking technologies such as cookies and SDKs to enhance your user experience and support website functionality. To learn more about Wendy's data processing, please review our Applicant Privacy Policy</value>
      <webElementGuid>17db8739-3dea-45df-9724-a1786f1291d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-policy-text&quot;)</value>
      <webElementGuid>dce8f05b-5a2c-433e-b462-9a4869153461</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='onetrust-policy-text']</value>
      <webElementGuid>46383604-259e-4784-9f77-6d2d8f8d9157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-policy']/div</value>
      <webElementGuid>fa1d51b5-02d4-4dc8-8528-b4db0e4e753f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Notice:'])[1]/following::div[1]</value>
      <webElementGuid>431c5844-b398-45ff-b4f0-d7c372bdd72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[1]</value>
      <webElementGuid>e9198193-60ec-4066-850d-0d4086d06bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>1f6b6cae-11d6-4b20-b2f5-2ec296712c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'onetrust-policy-text' and (text() = concat(&quot;Wendy&quot; , &quot;'&quot; , &quot;s uses tracking technologies such as cookies and SDKs to enhance your user experience and support website functionality. To learn more about Wendy&quot; , &quot;'&quot; , &quot;s data processing, please review our Applicant Privacy Policy&quot;) or . = concat(&quot;Wendy&quot; , &quot;'&quot; , &quot;s uses tracking technologies such as cookies and SDKs to enhance your user experience and support website functionality. To learn more about Wendy&quot; , &quot;'&quot; , &quot;s data processing, please review our Applicant Privacy Policy&quot;))]</value>
      <webElementGuid>0164194f-de8e-4cc3-a683-64aecba5c836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
