<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_5.381</name>
   <tag></tag>
   <elementGuidId>e1a85676-4acb-45a0-bde9-e81ea206c485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.header_bag_button.raise-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb14f50b-7ef5-42e0-98ef-0fa1ebcd3378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c68f6ad-bd76-4faf-811a-bad2ca7084e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_bag_button raise-button</value>
      <webElementGuid>6dcb4d0c-ba58-4d04-a547-03f87696e36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$5.381</value>
      <webElementGuid>e1c2c60e-a24e-4d6d-af8b-b77501915ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner&quot;)/div[@class=&quot;common order-header-container container-fluid&quot;]/div[@class=&quot;container order-funnel&quot;]/div[@class=&quot;account-location-container order-funnel&quot;]/div[@class=&quot;header-bag-container align-right col-xs-8&quot;]/button[@class=&quot;header_bag_button raise-button&quot;]</value>
      <webElementGuid>45eeff69-bffc-484e-9b74-0ff96748e9ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>aea07b1b-9203-44d1-86d9-caa47bfead80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='banner']/div[2]/div/div[3]/div[2]/button</value>
      <webElementGuid>98168240-5658-4086-be5a-5ad7ba86c7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Location'])[1]/following::button[1]</value>
      <webElementGuid>d66f8d06-4135-4267-80f5-33dff49997f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guest Checkout'])[1]/following::button[2]</value>
      <webElementGuid>ab8906db-ca3e-44db-a028-001b6d55fe92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stay hungry, my friends.'])[1]/preceding::button[1]</value>
      <webElementGuid>1b6b7908-79d4-42aa-9830-ffc9a74df5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>63d97324-5004-4f7c-9be7-f672cdd672b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '$5.381' or . = '$5.381')]</value>
      <webElementGuid>90d07c4e-463c-497d-8eeb-6fde773088cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
