<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Job</name>
   <tag></tag>
   <elementGuidId>224085e5-1687-4adf-a8b8-e2d5c47caeee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sub.solid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='index']/section/article/h2/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a32de6df-e04e-4b37-be36-7224109e6dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub solid</value>
      <webElementGuid>64139b52-c3a4-4823-9bf0-c9063e809cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job</value>
      <webElementGuid>fe9e4624-d340-4ad7-8655-efcd9ca20fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index&quot;)/section[@class=&quot;hero&quot;]/article[@class=&quot;content&quot;]/h2[@class=&quot;white&quot;]/div[@class=&quot;sub solid&quot;]</value>
      <webElementGuid>d60d4372-7dfa-4f3b-88f9-9d3d817773d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='index']/section/article/h2/div</value>
      <webElementGuid>77176207-24b2-42e1-aa55-d053fbb6e2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::div[1]</value>
      <webElementGuid>a846f786-1952-4391-b566-d2d862e81fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword or Job#'])[1]/preceding::div[2]</value>
      <webElementGuid>ab39b5a8-8235-451b-a5f9-6b9f7e935946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job']/parent::*</value>
      <webElementGuid>01bbd46e-148c-4475-ac80-fdb11d70d1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/div</value>
      <webElementGuid>6aa887e1-d713-4fdd-9ecd-76f57d363983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Job' or . = 'Job')]</value>
      <webElementGuid>f6b68522-d604-4e50-b155-d35176e5709a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
