<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ThanksYour response has been recorded. _2b33fc</name>
   <tag></tag>
   <elementGuidId>607245b1-f3ff-494b-a2ff-86159964c962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vHW8K</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Thanks!')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b374730-bc8e-4211-84e7-1f88c285c0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vHW8K</value>
      <webElementGuid>d7a1dc8e-17e2-4d64-a787-2f2e4c603df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanks!Your response has been recorded. We will contact you as soon as possible. You may always contact us directly at 123-456-7890 for faster service. </value>
      <webElementGuid>07c713b6-0915-4fb2-babd-7bb70c6ed74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;HB1eCd-UMrnmb&quot;]/body[@class=&quot;D8bnZd&quot;]/div[@class=&quot;Uc2NEf&quot;]/div[@class=&quot;teQAzf&quot;]/div[@class=&quot;RH5hzf RLS9Fe&quot;]/div[@class=&quot;idZHHb&quot;]/div[@class=&quot;vHW8K&quot;]</value>
      <webElementGuid>59321524-67a4-41be-bcf4-ae2788afeb46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Request'])[2]/following::div[1]</value>
      <webElementGuid>5b47ae26-da30-40dc-a932-6a88c1f67793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit another response'])[1]/preceding::div[1]</value>
      <webElementGuid>2d8e0f87-bdcc-4643-88cb-f8dcae1e2128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanks!']/parent::*</value>
      <webElementGuid>7d0e5279-3edd-4680-a185-0b1725551288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>5f94f109-4754-4942-a533-d3e23f3d5849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thanks!Your response has been recorded. We will contact you as soon as possible. You may always contact us directly at 123-456-7890 for faster service. ' or . = 'Thanks!Your response has been recorded. We will contact you as soon as possible. You may always contact us directly at 123-456-7890 for faster service. ')]</value>
      <webElementGuid>921c03a2-99c2-4c4b-89ba-0bc046f4f5c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
