<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_This is a required question</name>
   <tag></tag>
   <elementGuidId>f0563a9c-346f-4474-8235-0df6ad7843b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.RHiWt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i13']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>958899f5-839b-443b-bb98-c5a883dd22c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RHiWt</value>
      <webElementGuid>ab8c3563-9359-4b70-ba93-6083af19cbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a required question</value>
      <webElementGuid>a033660d-e437-4b95-99d1-dea3784a6f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i13&quot;)/span[@class=&quot;RHiWt&quot;]</value>
      <webElementGuid>4804a94e-f895-435e-987e-bde205a096d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i13']/span</value>
      <webElementGuid>e5dc3c36-b3db-4462-a7da-77e92b164432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the product number'])[1]/following::span[1]</value>
      <webElementGuid>c42d5bd0-a4ff-4b73-b4f9-6492f1af0916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[1]</value>
      <webElementGuid>5d9a97e8-b877-4853-8214-585b15c0d565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What color(s) would you like to order?'])[1]/preceding::span[1]</value>
      <webElementGuid>206b4f09-0141-404e-806d-b5e2973c37fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='color 1'])[1]/preceding::span[2]</value>
      <webElementGuid>606bb276-b2d2-439e-b281-e4a560d55b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a required question']/parent::*</value>
      <webElementGuid>f00656e2-6acb-4a1f-a649-d8fb03553b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>e72d9e94-e429-499c-b78f-f3902a69ba4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'This is a required question' or . = 'This is a required question')]</value>
      <webElementGuid>d5cb6b02-370e-4681-aac2-5f18e563c6ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
