<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_XS</name>
   <tag></tag>
   <elementGuidId>43cfcdd1-90e7-49cf-abdb-720fa28cd958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mG61Hd']/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/span/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.docssharedWizToggleLabeledContainer.ajBQVb.N2RpBe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d5c9d629-49aa-4d0c-9ae7-541578bd5caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>i9</value>
      <webElementGuid>760bef00-5a0e-465a-ae9c-f1ea6e2d6713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>docssharedWizToggleLabeledContainer ajBQVb N2RpBe</value>
      <webElementGuid>58bdc82d-d89a-420a-84f7-3aec818b458f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XS</value>
      <webElementGuid>2e03a41c-906d-4f25-841a-1052d4ece0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mG61Hd&quot;)/div[@class=&quot;RH5hzf RLS9Fe&quot;]/div[@class=&quot;lrKTG&quot;]/div[@class=&quot;o3Dpx&quot;]/div[@class=&quot;Qr7Oae&quot;]/div[1]/div[@class=&quot;geS5n&quot;]/div[@class=&quot;oyXaNc&quot;]/div[1]/div[@class=&quot;lLfZXe fnxRtf cNDBpf&quot;]/span[@class=&quot;H2Gmcc tyNBNd&quot;]/div[@class=&quot;SG0AAe&quot;]/div[@class=&quot;nWQGrd zwllIb&quot;]/label[@class=&quot;docssharedWizToggleLabeledContainer ajBQVb N2RpBe&quot;]</value>
      <webElementGuid>2397a317-67a7-4359-9089-ee6c6923c6f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mG61Hd']/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/span/div/div/label</value>
      <webElementGuid>0bf8fc20-c852-487f-a44d-800de4f3fea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[1]</value>
      <webElementGuid>e2a0d62e-e47e-422a-bf9f-df073c0a0a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shirt size'])[1]/following::label[1]</value>
      <webElementGuid>0fdfbf5c-7140-4b75-b0ca-226a56b9eb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::label[1]</value>
      <webElementGuid>e273dd6e-b8f3-4914-8fc0-af386936de48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>8257110c-3482-40c4-84d7-1d9b9067752d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'XS' or . = 'XS')]</value>
      <webElementGuid>d38615db-9e68-4919-afe6-f9654133e438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
