<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_This is a required question</name>
   <tag></tag>
   <elementGuidId>68a9e750-4c9e-40ec-b796-20a3bec41d5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.RHiWt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i3']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16c73c0f-20b6-48b8-855f-3d73b42ec791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RHiWt</value>
      <webElementGuid>d64cbf5d-981c-4b59-bf29-ca27aa17038d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a required question</value>
      <webElementGuid>1602c8af-4ed2-4560-9e34-ad11d2f25647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i3&quot;)/span[@class=&quot;RHiWt&quot;]</value>
      <webElementGuid>0b7250c0-a989-4e65-bc96-cea72334c14c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i3']/span</value>
      <webElementGuid>195c13be-1a06-411e-bdb7-c5613e36a0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Very much'])[1]/following::span[1]</value>
      <webElementGuid>c8e0398b-561d-4159-ab50-c558465137ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not very'])[1]/following::span[1]</value>
      <webElementGuid>2fbc6fe6-663e-4a21-9204-1899ff6939c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How relevant and helpful do you think it was for your job?'])[1]/preceding::span[1]</value>
      <webElementGuid>32e09472-0746-46d2-a808-5a739a7e3bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[2]</value>
      <webElementGuid>5ffe5825-e903-4d9a-8575-8a8c924a25b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a required question']/parent::*</value>
      <webElementGuid>19499080-85b5-4199-b222-612a2ff345e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>84c8b1a2-e9b7-4117-b105-584375495bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'This is a required question' or . = 'This is a required question')]</value>
      <webElementGuid>db91fbbc-a67c-412c-b77d-572bd87552e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
