<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>38e0d06d-1f82-4979-903b-002c3b706971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.fd-dropdown__close_btn.concession-announcement__close-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='concession-announcement']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d922472-e00a-4ebf-952d-f372ad84bb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fd-dropdown__close_btn concession-announcement__close-btn</value>
      <webElementGuid>3c33eb6a-4010-4368-9f07-5e977e8aa562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-overlay-i-d</name>
      <type>Main</type>
      <value>fd-dropdown-concessionAnnouncement</value>
      <webElementGuid>de3f8d1a-ade2-46d4-9d76-87bbdbfd82b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>a31eddf4-fdb2-4fc5-9a87-1a404965cbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concession-announcement&quot;)/button[@class=&quot;fd-dropdown__close_btn concession-announcement__close-btn&quot;]</value>
      <webElementGuid>d25d8887-b345-4bf1-90ef-64a062eac73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='concession-announcement']/button</value>
      <webElementGuid>7fd67be2-49bd-4c61-9090-1c1584ed8568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Feature'])[1]/following::button[1]</value>
      <webElementGuid>ada93583-9cd7-421c-b28f-923b0706f3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theaters'])[1]/following::button[1]</value>
      <webElementGuid>83625764-388a-427a-9e65-de852f87e794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='At Home'])[1]/preceding::button[1]</value>
      <webElementGuid>5396aab0-8d7f-4be5-a672-4e7062c2eb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movie News'])[1]/preceding::button[1]</value>
      <webElementGuid>8c06bffa-bb6a-4ac2-a99a-bb3af27ff504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>19507103-4b4c-4bb6-92b2-cb1ac0def74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/button</value>
      <webElementGuid>8ca71e6f-5fd6-4124-8c03-e6f9a05a6518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>99906b41-bba7-40be-851d-6e6308f81402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
