<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Go to previous films_fd-carousel__img</name>
   <tag></tag>
   <elementGuidId>51645030-2bff-4986-a389-87dc28c7c440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fd-carousel__img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='splide02-slide01']/a/figure/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d5e26398-3399-42e6-84ab-cc2117f155b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Deadpool &amp; Wolverine (2024) Poster</value>
      <webElementGuid>0aba6a5a-efbd-4074-ab18-c5a20f82464f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fd-carousel__img</value>
      <webElementGuid>93b260d3-b034-4047-a7f4-a72342198dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>548c05be-43eb-47f0-81c7-edd5c7b39955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/234516/DeapoolAndWolverine_2024.jpg</value>
      <webElementGuid>81a06145-9f91-42b7-a333-427bf323412d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide02-slide01&quot;)/a[@class=&quot;js-fd-carousel-focus-elem fd-carousel__link&quot;]/figure[@class=&quot;fd-carousel__fig&quot;]/div[@class=&quot;fd-carousel__img-wrap&quot;]/img[@class=&quot;fd-carousel__img&quot;]</value>
      <webElementGuid>f00666ed-b674-4bc7-b89b-c69cca893a68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='splide02-slide01']/a/figure/div/img</value>
      <webElementGuid>e90f0a67-3f9b-4a3e-8554-d12317f6db5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Deadpool &amp; Wolverine (2024) Poster']</value>
      <webElementGuid>d4c80d6f-35a3-4a37-9748-c5c68db30337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>d50e17bf-128e-467f-b4de-7229060cf11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Deadpool &amp; Wolverine (2024) Poster' and @src = 'https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/234516/DeapoolAndWolverine_2024.jpg']</value>
      <webElementGuid>7e1110b0-7f6e-443e-8369-c3ca509f4458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
