<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Skip to Main Content_q</name>
   <tag></tag>
   <elementGuidId>a0495a0a-a0fa-4c35-82c0-cbe35bb44b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-header-search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='global-header-search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b663e3ea-025a-4cb2-a1c6-c0fc5b8c963e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search by city, state, zip or movie</value>
      <webElementGuid>22e42cc9-028f-4edb-8b67-428bf2ff04db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-bar__search-input</value>
      <webElementGuid>6d218804-9cc4-4f9a-af71-13cb06a7dbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-header-search-input</value>
      <webElementGuid>f946e5bc-a842-40b4-bcdf-fcddab3cc715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>c34ffa66-2e9a-4a28-bfca-3be43662ed40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by city, state, zip or movie</value>
      <webElementGuid>18c2ba5b-0faf-4056-b64c-552c3a3d2fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afbadcb9-8561-484f-92de-d1c0b83a854a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9acd4d9c-6121-493b-b377-ccbc2bb4bfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header-search-input&quot;)</value>
      <webElementGuid>4e88f2ee-fe4d-40cb-9a80-436ee5e666d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='global-header-search-input']</value>
      <webElementGuid>5b92e275-d617-4ae9-98bc-806611b4c91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='global-search']/form/div/div/input</value>
      <webElementGuid>1b813289-52fd-44e7-a31f-42492727ffc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f1f31949-c0b8-474e-be88-957d69827a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'global-header-search-input' and @name = 'q' and @placeholder = 'Search by city, state, zip or movie' and @type = 'text']</value>
      <webElementGuid>69cf9f9d-9123-4c50-83da-6ed51314a919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
