<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_At Home</name>
   <tag></tag>
   <elementGuidId>7a29f2b9-a0b3-4a17-9a44-599881b81c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vudu-link > span.nav-bar__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='vudu-link']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ba2479f-8b46-4f75-92b7-66ed823aad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-bar__text</value>
      <webElementGuid>f5b53aa8-5f63-4e54-ba98-81c1a46b5484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>At Home</value>
      <webElementGuid>cb30b219-b6ee-4c04-b77f-73a209534d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vudu-link&quot;)/span[@class=&quot;nav-bar__text&quot;]</value>
      <webElementGuid>2ed2e3e7-4508-4aaa-8ed4-54da6113da70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='vudu-link']/span</value>
      <webElementGuid>81febc4d-ba22-4f6b-b718-b51b0f68fcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[1]</value>
      <webElementGuid>7c87861a-acd8-4ecb-ab13-1490ac835813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Feature'])[1]/following::span[1]</value>
      <webElementGuid>d08f6846-54fa-4440-98b6-a9ffce14b98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movie News'])[1]/preceding::span[1]</value>
      <webElementGuid>b115819c-e1b0-4471-8800-fc1038cc64c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In/Join'])[1]/preceding::span[2]</value>
      <webElementGuid>8675a83b-1f8f-4a18-b80e-8955cbce949b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='At Home']/parent::*</value>
      <webElementGuid>1517f81a-a969-4032-ab7a-92b71ab86357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>280ad1bf-62dd-49c1-8d33-bd003476d418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'At Home' or . = 'At Home')]</value>
      <webElementGuid>ea39786d-fa81-4168-8090-7c771f445c5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
