<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deal_2_text</name>
   <tag></tag>
   <elementGuidId>ddb60df3-95fd-40ad-bf1a-333fb8756e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pdp-product-title-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b1a60998-e0a9-4332-9c88-6f2a4ffb4a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fe064f5c-0 WObnm h-text-bold h-margin-b-none h-margin-b-tiny</value>
      <webElementGuid>18598d62-ba8e-412b-953f-97c03645e4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>product-title</value>
      <webElementGuid>285c8cb7-f392-43de-b369-d2bfeffdede1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pdp-product-title-id</value>
      <webElementGuid>a0be4575-43ee-4eb1-9e0a-06e10c838968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Peakform Folding C Table Black</value>
      <webElementGuid>d894e087-9510-4a9a-a787-0c8b23646b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp-product-title-id&quot;)</value>
      <webElementGuid>61862bc3-728d-46ee-89c7-62352449e49e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='pdp-product-title-id']</value>
      <webElementGuid>54a0a265-a4f3-4484-85ab-b5e2daa2c42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='above-the-fold-information']/div[3]/h1</value>
      <webElementGuid>2e486386-4f39-45de-a04a-7d022d006f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload photo'])[1]/following::h1[1]</value>
      <webElementGuid>4fe772d5-a4d0-4466-a7d5-2f320c5d9841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$19.99'])[1]/preceding::h1[1]</value>
      <webElementGuid>12ba487f-fbd5-4cf1-a994-87f1aff41262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Peakform Folding C Table Black']/parent::*</value>
      <webElementGuid>22ec5eac-4b45-4f04-8f3b-1f844b246ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>5bd18baa-1b82-4748-be70-a3edf2ff0cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'pdp-product-title-id' and (text() = 'Peakform Folding C Table Black' or . = 'Peakform Folding C Table Black')]</value>
      <webElementGuid>5da8b519-b63d-4ad2-909f-082a6cc36f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;pageBodyContainer&quot;]/div/div[1]/div/div[3]/div/div/ul/li[1]/a/div/div[2]</value>
      <webElementGuid>dc76e342-c64f-4267-8f51-af0bee72e162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
