<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jr. Bacon Cheeseburger Biggie Bag</name>
   <tag></tag>
   <elementGuidId>6faab257-3aff-4642-b944-85fa2671d560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#review-item-title-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Bag'])[1]/following::div[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>42aadf9c-15d0-41ff-b912-41ca53708c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>review-item-title-0</value>
      <webElementGuid>77616635-ee6b-49eb-99c6-cc1e7ade0449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-options-title</value>
      <webElementGuid>0f597fd4-f2f9-40ad-9ddc-3542e22f55f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1424cd57-f64d-4051-b16f-a300d47adc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jr. Bacon Cheeseburger Biggie™ Bag </value>
      <webElementGuid>86896c77-19b4-4ab7-8dd6-b823b385bcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-item-title-0&quot;)</value>
      <webElementGuid>be602ed5-7edc-44b1-9734-e119411df63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='review-item-title-0']</value>
      <webElementGuid>2990db63-ea5b-4e09-be4a-9b48a1e12cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-item-0']/div/div[2]/div/div</value>
      <webElementGuid>9f7d8d43-2c2a-48a9-8182-56653d885b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Bag'])[1]/following::div[9]</value>
      <webElementGuid>e4267985-489d-4c45-a698-a7ca774ed84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::div[16]</value>
      <webElementGuid>59157fd0-1071-4902-85b0-275e46db888d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jr. Bacon Cheeseburger'])[1]/preceding::div[4]</value>
      <webElementGuid>02736ec3-59da-49a0-9baa-a547cb9036b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sweet and Sour Dipping Sauce'])[1]/preceding::div[13]</value>
      <webElementGuid>ff939608-6e6f-49ba-89f1-26f8e1b56b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jr. Bacon Cheeseburger Biggie™ Bag']/parent::*</value>
      <webElementGuid>2b6d0a3b-2719-4a9e-a5c3-b5af02b1d970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[2]/div/div</value>
      <webElementGuid>7f351bf8-3f37-413e-83cd-9f74637781fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'review-item-title-0' and (text() = 'Jr. Bacon Cheeseburger Biggie™ Bag ' or . = 'Jr. Bacon Cheeseburger Biggie™ Bag ')]</value>
      <webElementGuid>5c33a4d0-a429-4616-bbe0-b0b1e14687de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
