<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Deals</name>
   <tag></tag>
   <elementGuidId>9ecbde92-f293-446c-9487-f89677911475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerPrimary']/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a0a3f2f-ecc7-41d2-afa1-17063dfd1417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92753b92-820a-46b8-8993-25c56f80df36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Deals</value>
      <webElementGuid>2eb6e8e8-9a91-47ea-96ec-240019db8792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>@web/Header/MainMenuLink</value>
      <webElementGuid>f5c7666b-598d-426e-8c9b-8971fd721e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/weekly-deals/-/N-4xw74?prehydrateClick=true</value>
      <webElementGuid>59f261c4-32ac-4539-b641-6f78b33813d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ab4ee1d1-1 sc-ab4ee1d1-3 bYXfno daqCdx</value>
      <webElementGuid>d352f75d-ff49-4bd6-963a-14a1e30ecebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deals</value>
      <webElementGuid>71823908-7738-48ff-9eb7-d4568973e8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerPrimary&quot;)/div[@class=&quot;sc-ab4ee1d1-4 idfyjy&quot;]/a[@class=&quot;sc-ab4ee1d1-1 sc-ab4ee1d1-3 bYXfno daqCdx&quot;]</value>
      <webElementGuid>34bebfc8-9232-41ca-a132-16a4ac0325a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerPrimary']/div[3]/a</value>
      <webElementGuid>f8920fb9-59c9-4d7d-8fa0-652a8d736a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Deals')]</value>
      <webElementGuid>e004e474-4617-405a-bc27-aec79293285f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/following::a[2]</value>
      <webElementGuid>21ff566f-8d86-4f54-b1a6-3557626e80dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Stores'])[1]/following::a[5]</value>
      <webElementGuid>7e362b64-2c97-4d99-ad98-2e4b247c7d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New &amp; featured'])[1]/preceding::a[1]</value>
      <webElementGuid>22352203-92cd-43b5-beeb-aeb8db76aea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pickup &amp; delivery'])[1]/preceding::a[2]</value>
      <webElementGuid>941dc6d3-e370-4731-aa2e-51821e5ce4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deals']/parent::*</value>
      <webElementGuid>0eb1deff-2227-43b0-92e5-620f9ceae311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/weekly-deals/-/N-4xw74?prehydrateClick=true')]</value>
      <webElementGuid>d9e9be3c-851b-4a6f-af60-79c5359ad71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>53d38b8c-bf50-449d-938b-997ac1e1c1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/weekly-deals/-/N-4xw74?prehydrateClick=true' and (text() = 'Deals' or . = 'Deals')]</value>
      <webElementGuid>1070e247-1d97-466b-b39c-4ad4b5677829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
