<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Top Deals</name>
   <tag></tag>
   <elementGuidId>dd65844e-a40f-4de9-afc2-5bd26835b893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.styles_wrapper__YYaWP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overlay-:R13kmuqlm:']/ul/li/a/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a93c74a-e02b-421f-900a-ba4343090b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_wrapper__YYaWP</value>
      <webElementGuid>b4644820-a748-4f28-a5ce-1cea500234a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Top Deals</value>
      <webElementGuid>c04be700-522c-44ca-ba41-77619515175c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlay-:R13kmuqlm:&quot;)/ul[@class=&quot;sc-859e7637-3 dTUnnZ&quot;]/li[1]/a[@class=&quot;sc-676073c3-0 sc-778d5df3-0 iJrLGj kfwmyB&quot;]/div[@class=&quot;styles_baseCell__zb2BN styles_cellSkinny__Fjdj8&quot;]/span[@class=&quot;styles_wrapper__YYaWP&quot;]</value>
      <webElementGuid>4e894138-bf58-4afc-bcf3-e2d0489e4574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overlay-:R13kmuqlm:']/ul/li/a/div/span</value>
      <webElementGuid>06fe3bfb-1121-4f3e-8865-f6809a5250a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/following::span[1]</value>
      <webElementGuid>d19c3ffc-f325-4d4c-8771-d9e59f6582c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy policy'])[1]/following::span[2]</value>
      <webElementGuid>f8de72a0-6288-4392-947d-9d9476b7eadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target Circle Deals'])[1]/preceding::span[1]</value>
      <webElementGuid>819a2bc2-bcaa-4ba6-a68f-15fe89ea9f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekly Ad'])[2]/preceding::span[2]</value>
      <webElementGuid>9d9220ed-c3be-4246-85e1-ccda43c18f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Top Deals']/parent::*</value>
      <webElementGuid>cc06bf5a-3ad0-42ca-83d8-fd77e485f4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span</value>
      <webElementGuid>d502c654-057d-4122-8c63-b334406d38d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Top Deals' or . = 'Top Deals')]</value>
      <webElementGuid>891ef9f5-5ffe-443f-b57d-02723dfe4cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
