<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fandango Media Brands_join-now-submit-btn</name>
   <tag></tag>
   <elementGuidId>0b36b78f-bf19-46d8-bc7d-87bc90a6cd85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#join-now-submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='join-now-submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f78d011f-931c-4792-aefa-ecec718898b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>join-now-submit-btn</value>
      <webElementGuid>4d1277ce-ad04-4fa6-a54f-46229895c085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>d777fec6-ec9c-4545-8b22-29c2d9c081e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>48c53d2f-c43d-4879-9711-4dba823516f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Join now for free</value>
      <webElementGuid>ff94b21d-b546-4d8b-8ea2-66311aa9cce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;join-now-submit-btn&quot;)</value>
      <webElementGuid>98416523-50b4-4356-b7d6-33d45876d020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='join-now-submit-btn']</value>
      <webElementGuid>1d02584b-a5a1-43a1-9b6d-2e66d5246cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='join-now-form']/input</value>
      <webElementGuid>9d3cc76d-d384-447c-aef4-6b5e92c425ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>962d7a09-810b-4857-80c9-ebd8b0071bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'join-now-submit-btn' and @type = 'submit']</value>
      <webElementGuid>e0367637-e512-4013-a5e1-82ceb15cee2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
