<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The Garfield Movie (2024)  2024</name>
   <tag></tag>
   <elementGuidId>aa91e1b9-1a60-4963-89ee-3503a6392978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mainContainer-styles__default--QDt76</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactApp']/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/span/div/div/div/div/div/div/div/div/div[4]/div/div/a/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c358f9cf-f418-4d2f-aa73-b756322f24ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mainContainer-styles__default--QDt76</value>
      <webElementGuid>c3a0b729-a9ae-48f1-98b2-57d3224556d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Garfield Movie (2024)  2024 </value>
      <webElementGuid>60e79b00-b436-40ed-934e-b42f4e05f90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactApp&quot;)/div[@class=&quot;nr-medium-page main-page-container&quot;]/div[@class=&quot;progressOverlay__body--Mrr2x&quot;]/div[@class=&quot;nr-page-body&quot;]/div[2]/div[@class=&quot;nr-mt-30&quot;]/div[@class=&quot;uxPage__uxPageContainer--pXwK6&quot;]/div[2]/div[1]/div[@class=&quot;uxPage__uxPageRow--zRM20&quot;]/div[@class=&quot;row nr-m-0&quot;]/div[@class=&quot;col-xs-12 nr-p-0&quot;]/div[@class=&quot;nr-mb-32&quot;]/div[2]/span[1]/div[@class=&quot;nr-pt-5&quot;]/div[@class=&quot;carousel-default-styles__hoverContainer--bcxAx&quot;]/div[@class=&quot;carousel-default-styles__carousel--oIJH7 o-hidden&quot;]/div[@class=&quot;carousel-default-styles__fullWidth--hHVJr&quot;]/div[@class=&quot;carousel-default-styles__rows--F3fVn&quot;]/div[@class=&quot;carousel-default-styles__animation--ZTmWk&quot;]/div[1]/div[@class=&quot;carousel-default-styles__row--V1C7F carousel-default-styles__fullWidthRow--iRqbR&quot;]/div[@class=&quot;carousel-default-styles__item--V3tCG&quot;]/div[@class=&quot;uxPage__uxElementPoster--Nzhd5&quot;]/div[@class=&quot;contentPosterWithMetadata__containerWithLink--CYKg9&quot;]/a[1]/div[@class=&quot;contentPosterWithMetadata__container--MsDQx contentPosterWithMetadata__loaded--KVENb content-poster&quot;]/div[@class=&quot;contentPosterWithMetadata__metadata--Ntyf2 contentPosterWithMetadata__loaded--KVENb&quot;]/div[@class=&quot;mainContainer-styles__default--QDt76&quot;]</value>
      <webElementGuid>f5aebddb-c9ee-4fc8-a51b-9136b27d6f7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactApp']/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/span/div/div/div/div/div/div/div/div/div[4]/div/div/a/div/div[2]/div</value>
      <webElementGuid>48d1a090-32da-4413-9bb7-b8f4ac8b5f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/following::div[36]</value>
      <webElementGuid>aa9fe0de-61f5-4417-8070-e8aa4c9acced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium New Releases'])[1]/following::div[37]</value>
      <webElementGuid>46bc15d3-4915-4fae-b22f-b1aebfa7556a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New to Rent'])[1]/preceding::div[19]</value>
      <webElementGuid>be806ac6-9057-4c9f-b7ed-e07af6555146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/div</value>
      <webElementGuid>f6cd773f-e9ea-4227-8ad2-bf183688cdf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'The Garfield Movie (2024)  2024 ' or . = 'The Garfield Movie (2024)  2024 ')]</value>
      <webElementGuid>f8ecb84f-0cf4-4aaf-a7b0-4b6dbf03db4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
