<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Longlegs (2024) Released Fri, July 12th_d5d096</name>
   <tag></tag>
   <elementGuidId>a2869191-cf5c-47bf-8f4d-90fc59cb97f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='page']/div/div/div/div[2]/ul/li[5]/a/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1be95923-e746-4cf7-a312-0754ecd179a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f-logo-bg poster-card--img poster-card--img__small visual-thumb</value>
      <webElementGuid>a23d6845-29ea-44bb-a5aa-8810d4eee576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster--dark-mode.png/0/images/MasterRepository/fandango/234520/AQPD1_DOM_Online_Payoff_1-Sheet_05_FIN8A.jpg</value>
      <webElementGuid>fd22c723-d8aa-4399-bdc6-0485e742aa0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>125edea8-ee28-4948-8f18-84d79e10840a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;now-playing&quot;]/div[@class=&quot;row dark__section&quot;]/div[@class=&quot;width-75 tablet-width-100 mobile-width-100&quot;]/div[@class=&quot;now-playing__wrap&quot;]/ul[@class=&quot;browse-movielist&quot;]/li[@class=&quot;poster-card poster-card__fluid browse-movielist--item dark__section&quot;]/a[1]/span[@class=&quot;poster-card--img-wrap visual-container&quot;]/img[@class=&quot;f-logo-bg poster-card--img poster-card--img__small visual-thumb&quot;]</value>
      <webElementGuid>7a3e1890-5c94-492b-b537-b4db0e937a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='page']/div/div/div/div[2]/ul/li[5]/a/span/img</value>
      <webElementGuid>10712c47-b202-4de5-b3f2-d76c3e50cd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster--dark-mode.png/0/images/MasterRepository/fandango/234520/AQPD1_DOM_Online_Payoff_1-Sheet_05_FIN8A.jpg')]</value>
      <webElementGuid>ee3d1442-ff36-4261-8c6e-2be87dfbcfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span/img</value>
      <webElementGuid>92b50d76-7a25-4d8f-b63b-ffe40d0c8412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster--dark-mode.png/0/images/MasterRepository/fandango/234520/AQPD1_DOM_Online_Payoff_1-Sheet_05_FIN8A.jpg']</value>
      <webElementGuid>4c23a14d-e7f8-4506-96c3-12e076b236a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
