<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carryout</name>
   <tag></tag>
   <elementGuidId>2bd5c79d-dd29-4dd0-bff5-e195778110de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>772ae7da-8659-4b5a-b3f9-b8ba857844b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fulfillment-img-name</value>
      <webElementGuid>841bf24b-192e-4d9f-b372-693d99e6f46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3549a4c0-2060-4826-a0cb-b508b1840746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-2</value>
      <webElementGuid>9858509a-4939-42ce-aeb6-d19babd71308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carryout</value>
      <webElementGuid>743297b9-3925-43dc-968c-f37b440744ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;common-header&quot;]/div[@class=&quot;main-content-container margin-adjust-for-sub-header&quot;]/div[@class=&quot;main-landing-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;bottom-half&quot;]/div[@class=&quot;location-pickup-container row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;location-fulfilment-container col-md-7&quot;]/div[@class=&quot;pickup-container&quot;]/div[@class=&quot;desktop-pickup col-sm-6 align-center&quot;]/div[@class=&quot;pickup-methods msg-available&quot;]/div[@class=&quot;radios&quot;]/div[@class=&quot;radio-group location-modal&quot;]/div[1]/div[@id=&quot;radio-2&quot;]</value>
      <webElementGuid>7ffec1a0-7b77-449b-963d-fce340b94a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radio-2']</value>
      <webElementGuid>8edd859e-2a57-49d9-85bb-e06a17b6f852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div/div[2]/div[3]/div/div/div[2]/div/div/div/div[3]/div/div</value>
      <webElementGuid>23d2cb14-1d2e-4d6b-8466-76e26bc3a80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[2]/following::div[4]</value>
      <webElementGuid>53ce2e83-bfee-44d2-9242-b22cd3fa5608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dine in'])[1]/following::div[6]</value>
      <webElementGuid>897e4a49-e445-45e9-a73f-4af3a6e15884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[3]/preceding::div[1]</value>
      <webElementGuid>ef7f402d-35b9-4af2-a408-24b32d5df5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div</value>
      <webElementGuid>d6d7ca38-2460-450e-9a88-9ef26bf94979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radio-2' and (text() = 'Carryout' or . = 'Carryout')]</value>
      <webElementGuid>17f89b49-d76c-4c01-a16f-ab9b1c999f63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
