<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Coca-Cola Freestyle_combo-option-side-1</name>
   <tag></tag>
   <elementGuidId>00b2eae4-0994-4e1b-9165-baab7da488d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo-side-1-40401</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='options-container']/div/button)[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a392e0c6-4cd9-41fc-90e3-fd89d1919f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combo-side-1-40401</value>
      <webElementGuid>6b132b21-5b05-4e87-a16b-00e54d549e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>combo-option-side-1</value>
      <webElementGuid>97ef9e8c-fab0-4f7a-8f39-c0d54e6f354f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>combo-option-side-1</value>
      <webElementGuid>3eb93714-becc-40e8-a975-8b54d184250a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4ca804c-89c6-4e15-851a-04aea0f87834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
              outer-boundary no-border full-image </value>
      <webElementGuid>c5464f61-b825-4616-9a0c-9e7dc75208ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sweetened Iced Tea</value>
      <webElementGuid>85acc2bc-2efc-4530-ae9c-23bb441907c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo-side-1-40401&quot;)</value>
      <webElementGuid>a594e90c-7e39-4772-9d18-a74707cff960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='combo-side-1-40401']</value>
      <webElementGuid>6d67dd7e-d149-4732-8567-9b8b3fa7ef5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='options-container']/div/button)[11]</value>
      <webElementGuid>c860bd55-5c4f-4917-8684-ba571cb7ff08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coca-Cola Freestyle'])[1]/following::button[1]</value>
      <webElementGuid>49e25754-ac64-41b3-b923-0afdd14f25f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sweetened Iced Tea'])[1]/preceding::button[1]</value>
      <webElementGuid>15f59b4d-ee58-4296-82b4-a87de8eede9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pineapple Mango Lemonade'])[1]/preceding::button[2]</value>
      <webElementGuid>56105ba4-1668-4793-8349-9158f8994ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/button</value>
      <webElementGuid>7160d1ee-fdad-4ac1-b5dd-53f33c97b11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'combo-side-1-40401' and @name = 'combo-option-side-1' and @type = 'button']</value>
      <webElementGuid>b465f702-9cb4-4cae-b64a-9b9bdd9620d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
