<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Choose your  nugget_combo-option-side-0</name>
   <tag></tag>
   <elementGuidId>51830cc5-d6fb-45d2-8232-da4fe9efca4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo-side-0-41071</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='combo-side-0-41071']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff138398-367e-4e01-a45d-81dc4ef9df8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combo-side-0-41071</value>
      <webElementGuid>0b5756b1-e025-4d9a-ae4a-1ffa5bc0afa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>combo-option-side-0</value>
      <webElementGuid>fcbb439b-65ec-4299-9906-5654c2a253dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>combo-option-side-0</value>
      <webElementGuid>1183f92c-7d17-4b17-8008-0d6550e81330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1bdd7215-e59f-451f-82a9-7062e0c5f0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
              outer-boundary no-border full-image </value>
      <webElementGuid>97e058a6-9f45-4bbb-a921-564d7ca0edca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>4 PC. Chicken Nuggets</value>
      <webElementGuid>fcf8ff50-dec3-43ce-b00e-03ed8d75864c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo-side-0-41071&quot;)</value>
      <webElementGuid>b56b9c5b-5594-4c50-a9cf-9f56798275d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='combo-side-0-41071']</value>
      <webElementGuid>edb9c421-58d8-4d70-bbe2-bab50dfae56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='options-container']/div/button</value>
      <webElementGuid>b9110022-222c-46cf-882f-3bd50ab84f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jr. Bacon Cheeseburger Biggie™ Bag'])[1]/following::button[1]</value>
      <webElementGuid>b51a4c41-bb9e-408a-af48-e02155e4976a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coca-Cola Freestyle'])[1]/preceding::button[10]</value>
      <webElementGuid>6fde1e9d-484b-43e5-9695-7325717512e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/button</value>
      <webElementGuid>d5c9854b-8ce9-49f1-bf0c-5e7cdf79f9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'combo-side-0-41071' and @name = 'combo-option-side-0' and @type = 'button']</value>
      <webElementGuid>b926655c-665a-4f83-bc4d-dde355b6f526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
