<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buttermilk Ranch Dipping Sauce_combo_567144</name>
   <tag></tag>
   <elementGuidId>b0283add-f56b-4bdc-b1de-73a8518ac6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo-side-71057-side-modifier-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='combo-side-71057-side-modifier-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c466285a-9fff-42a1-866e-c11321b0abed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combo-side-71057-side-modifier-0</value>
      <webElementGuid>c3717951-92b7-4485-b69d-ed1566e216c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>combo-option-side</value>
      <webElementGuid>4a19286c-2742-47e5-bf05-0754a312f2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>combo-option-side</value>
      <webElementGuid>af19757f-8135-4b19-95fd-b79c160eb9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce8b878a-bb52-42d4-b83c-f58095203f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
              outer-boundary no-border full-image </value>
      <webElementGuid>78030096-ac0c-4363-ab4c-46c9f0fd5cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sweet and Sour Dipping Sauce</value>
      <webElementGuid>ad428b19-3de4-477d-963e-e7d5ed587806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo-side-71057-side-modifier-0&quot;)</value>
      <webElementGuid>e4b7acd6-ab54-4271-b94e-96768de2e69e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='combo-side-71057-side-modifier-0']</value>
      <webElementGuid>56234551-a048-4c73-9e21-3b0e668c606f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='options-container']/div/button)[33]</value>
      <webElementGuid>7a3adba6-cf91-4ca9-b30e-aa3a64a2619b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buttermilk Ranch Dipping Sauce'])[1]/following::button[1]</value>
      <webElementGuid>973106a0-62f0-4ca8-b09b-7cac189c44ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketchup'])[1]/following::button[2]</value>
      <webElementGuid>a97510b8-5d2f-49ec-bb7c-5cd3a63b748e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sweet and Sour Dipping Sauce'])[1]/preceding::button[1]</value>
      <webElementGuid>7d128b45-a35b-410b-b6c9-b3cbd5aaa8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Dipping Sauce'])[1]/preceding::button[2]</value>
      <webElementGuid>2855ab25-cf6a-42b0-a506-c42d17febafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[6]/div/button</value>
      <webElementGuid>8544da44-877a-4f8f-a80a-e521e4d38258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'combo-side-71057-side-modifier-0' and @name = 'combo-option-side' and @type = 'button']</value>
      <webElementGuid>ccfbd3db-a1bd-4776-99e3-c8fa2b21cb7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
