<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>30534356-b544-4e5d-9b5f-8c4f03888090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo-undefined-31476 > span.option-label > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='combo-undefined-31476']/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9a1468e-9893-4f43-8c0e-e3739b6d8bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.wendys.com/unified/assets/menu/pg-cropped/1761_small_US_en.png</value>
      <webElementGuid>6a27f0e9-cec7-4fa9-8a8a-68a4633c0095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>cfbb0126-a271-414f-8a9a-90862deb3dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo-undefined-31476&quot;)/span[@class=&quot;option-label&quot;]/img[1]</value>
      <webElementGuid>d5c08b7f-fe38-406b-bbe1-00c1bb65bf33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='combo-undefined-31476']/span/img</value>
      <webElementGuid>2ac8d338-c59a-4617-8963-0bbad17b4169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://app.wendys.com/unified/assets/menu/pg-cropped/1761_small_US_en.png')]</value>
      <webElementGuid>40d0a521-d329-4cfc-8f1a-2ae8baf9f2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span/img</value>
      <webElementGuid>14abbb16-6eae-45cd-abd6-a48b1c874dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://app.wendys.com/unified/assets/menu/pg-cropped/1761_small_US_en.png']</value>
      <webElementGuid>55d37e8c-89cb-4015-8649-55373011ff85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
